### ISSUE TITLE
provide convenient way to install latest Go stable version

### ISSUE THREAD

**Issue by bruceauyeung** [voidint/g#103]
**Describe the solution you'd like**
e.g. `g install latest`.
so users can install latest stable Go version even if they don't know what it is.

**Describe alternatives you've considered**
none

**Comment by jan-bar** [comment]
I use this scheme: `g install $(g ls-remote stable | tail -n1)`

However, when the latest version is already used, the preceding asterisk will cause the execution to fail，such as `* 1.20.7`

So I ended up using this command: `ver=$(g ls-remote stable | tail -n1) && g install ${ver:1}`

**Comment by voidint** [comment]
This feature will be added

**Comment by voidint** [comment]
This feature has been merged into the master branch
