### ISSUE TITLE
The function of golang1.20.0 version is abnormal

### ISSUE THREAD

**Issue by jan-bar** [voidint/g#105]
![image](https://github.com/voidint/g/assets/14202095/34e7c970-90e6-4dec-8b84-09b0d97227b8)

![image](https://github.com/voidint/g/assets/14202095/2554d0aa-670e-4e2d-af09-0473a608f7a0)

**Comment by voidint** [comment]
Naming changes resulting from new [proposals](https://github.com/golang/go/issues/57631). I will adapt as soon as possible.

**Comment by voidint** [comment]
Temporarily you can use the following instead: `g install 1.20.0`

**Comment by voidint** [comment]
Please use `g self update` to upgrade to the latest version.

**Comment by jan-bar** [comment]
@voidint available for work
