### ISSUE TITLE
ls-remote doesn't show correct version number of latest release

### ISSUE THREAD

**Issue by lwx-bupt** [voidint/g#106]
**Describe the bug/缺陷描述**
ls-remote doesn't show correct version number of latest release
**To Reproduce/缺陷复现步骤**
Type "./g ls-remote" in terminal.
**Expected behavior/期望行为**
  ……
  1.21.0
**Screenshots/实际运行结果截图**
  ……
  1.21
**Environments (please complete the following information)/运行环境:**
- OS[e.g. uname -a]
Windows 10
- g --version

g version 1.5.0
build: 2023-01-01T21:01:59+08:00
branch: master
commit: cec84a3f4f927adb05018731a6f60063fd2fa216

**Additional context/额外信息**

Go has changed the version number of the 1st release of a major version from 1.xx to 1.xx.0 since Go 1.21.
See: https://go.dev/doc/toolchain#versions

**Comment by voidint** [comment]
g self update
