### ISSUE TITLE
tls: bad record MAC

### ISSUE THREAD

**Issue by kubefay** [voidint/g#110]
**Describe the bug/缺陷描述**
执行 g install 1.19.1，提示 Local error: tls: bad record MAC

**Screenshots/实际运行结果截图**
![image](https://github.com/voidint/g/assets/28134721/df02d6d1-02c8-4685-b82f-03a258a7e9fc)

**Environments (please complete the following information)/运行环境:**
- OS[e.g. uname -a]
Linux Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- g --version
g version 1.5.2
build: 2023-09-05T21:47:23+08:00
branch: release/1.5.2
commit: dd615e5d

**Comment by voidint** [comment]
这应该属于偶发性的网络错误，是否能复现？

**Comment by kubefay** [comment]
是网络错误，换一个网络环境就好了
