### ISSUE TITLE
windows下，g ls-remote stable 命令无效

### ISSUE THREAD

**Issue by myproject** [voidint/g#112]
g ls-remote stable 不能正确拉出版本，g ls-remote 可以。
![image](https://github.com/voidint/g/assets/1639690/a246ae8c-1615-4f1d-b537-05e980c27631)

**Comment by voidint** [comment]
你应该是将`G_MIRROR`环境变量设置成了阿里云镜像，该镜像是无法区分出这些类别的，所以[统一返回的都是空](https://github.com/voidint/g/blob/master/internal/collector/aliyun/aliyun_collector.go#L62)。

**Comment by voidint** [comment]
至于阿里云镜像为什么无法区分，这个[PR](https://github.com/voidint/g/pull/100)中有相关的描述。

**Comment by myproject** [comment]
bingo~了解了。不过建议在程序返回空时增加个提示。
