### ISSUE TITLE
Goland中如何引用SDK

### ISSUE THREAD

**Issue by 1749335128** [voidint/g#117]
非常感谢作者停供给go开发者这样一个版本管理器。我在使用中遇到一点问题，目前我在windows上已经可以正常使用g命令了，并且下载了一个版本，执行go env命令都是可以正常使用的，唯一的问题是我不知道在goland中去导入我的go sdk。我几乎~./g/目录下的文件夹全部选择了一便都是这个错误。希望遇到能够帮助我的人
![image](https://github.com/voidint/g/assets/86713070/b920bfa3-9390-4a90-94ae-2d75f7d81b45)
这个是PATH配置：其它的都使用的是默认配置了。
![image](https://github.com/voidint/g/assets/86713070/cd3bd764-4b57-4cc7-8618-f7ab8ca94de1)
![image](https://github.com/voidint/g/assets/86713070/f180d844-c46f-4593-9bcf-2d2acef53e4d)
![image](https://github.com/voidint/g/assets/86713070/b0e7b8cc-5c2f-42a3-9142-2337b799d3aa)

**Comment by voidint** [comment]
`~/.go/go`是一个软连接，正常应该选择该目录，如果在 goland 中没法选择它，那么可能得更换一个 goland 版本，不知道你使用的是哪个版本？曾今也有 Windows 用户提过类似的 issue ，后来也是升级 goland 解决，本质上还是 goland 没有跟随软连接所导致。

**Comment by 1749335128** [comment]
抱歉，我确实更新了一下goland版本和重庆了一下，再次打开goland自动识别到了sdk。

**Comment by voidint** [comment]
ok
