### ISSUE TITLE
请问能否支持类似nvm fnm之类的星号*通配符

### ISSUE THREAD

**Issue by caihuach** [voidint/g#118]
**Is your feature request related to a problem? Please describe.**
g install 1.20 安装了1.20

**Describe the solution you'd like**
g install 1.20 可以安装1.20.* 比如最新版 1.20.11

**Describe alternatives you've considered**
g install 1.20.x/1.20.*

**Additional context**
无

感谢

**Comment by voidint** [comment]
- 会支持，但不会仅限于`*`，我在考虑将 npm 版本号的那套规则移植过来，比如[这样](https://juejin.cn/post/6983659602696994829)。
- #103 也提到过想要增加`latest`，都是类似的需求。

**Comment by voidint** [comment]
`master`分支已支持版本标识符功能（含通配符），如`g install 1.18.x`或者`g install 1.18.X`或者`g install '1.18.*'`。注意：`*`的方式需要将整个字符串用引号包裹。

完整规则如下：
```
- 具体版本号：如'1.21.4'
- 最新版本：latest
- 通配符：如'1.21.x'、'1.x'、'1.18.*'等
- 兼容某个主版本号：如'^1'、'^1.18'、'^1.18.10'等，在主版本号保持一致的前提下，次版本号和修订号均保持最新。
- 匹配某个主次版本号：如'~1.18'，在主次版本号保持一致的前提下，修订号保持最新。
- 大于某个版本：如'>1.18'，大于该版本的前提下，匹配最大的版本号。
- 小于某个版本：如'<1.16'，小于该版本的前提下，匹配最大的版本号。
- 版本区间：如'1.18 - 1.20'，匹配该区间范围内的最大版本。
```
