### ISSUE TITLE
切换版本后，vscode的go插件未更新，版本还是显示之前的，重启仍然保持现状。

### ISSUE THREAD

**Issue by Nuyoahhjh** [voidint/g#125]
![Snipaste_2023-12-14_09-58-10](https://github.com/voidint/g/assets/104013313/9bf3193d-5fb2-4091-a931-a7af7fb7aca9)

**Comment by voidint** [comment]
- 不知道你用的 vscode 是什么版本？我也使用的 vscode ，不过是 macOS 系统，并不存在你提到的这种情况。
- 另外，建议你看看 GOROOT 环境变量的值是否指向 g 家目录下的 go 目录。
- 我能想到的另外一种可能性是你为 vscode 指定了一个路径，也就是指向go 1.19.13。比如，像下面这样指定了 GOROOT 路径，那么即使通过 g 切换到了另一个版本，vscode 中显示的 go 版本也不会发生变化。否则，通过 reload window，状态栏中显示的 go 版本号就会改变了。
<img width="446" alt="image" src="https://github.com/voidint/g/assets/6327183/e71b768b-395f-4943-8f74-bc191bf29095">

**Comment by Nuyoahhjh** [comment]
感谢

**Comment by itxtoledo** [comment]
this worked for me:

.vscode/settings.json

```
{
    "go.goroot": "~/.g/go"
}
```

**Comment by voidint** [comment]
> this worked for me:
> 
> .vscode/settings.json
> 
> ```
> {
>     "go.goroot": "~/.g/go"
> }
> ```

不建议在这个配置文件中硬编码路径，本身 vscode 的 Go 插件就会从环境变量`GOROOT`中去自动读取。如果你这么设置了，假设还忘记了，下次自己改了环境变量，发现 vscode 中又不起作用了。本来只要改一处，现在变成得改两处。
