### ISSUE TITLE
g version 1.6.0 windows  G_HOME invalid 

### ISSUE THREAD

**Issue by China-Uncle** [voidint/g#126]
**Describe the bug/缺陷描述**
windows  G_HOME invalid

**To Reproduce/缺陷复现步骤**
![image](https://github.com/voidint/g/assets/39592981/e31b9fcc-deba-4a11-bd2d-ee250734288e)

**Expected behavior/期望行为**
Download to  D:\Program Files\Go\

**Screenshots/实际运行结果截图**
Download to %USERPROFILE%.go

**Environments (please complete the following information)/运行环境:**
- OS[e.g. uname -a]

- g -v

    ```shell

    ```

- go env

    ```shell

    ```

- echo $G_EXPERIMENTAL

    ```shell

    ```

- echo $G_HOME

    ```shell

    ```

- echo $G_MIRROR

    ```shell

    ```

**Additional context/额外信息**

**Comment by voidint** [comment]
README中有说明，须先开启`G_EXPERIMENTAL`。

**Comment by China-Uncle** [comment]
多谢。之前的版本没有看到这个设置。设置之后的确可以了。
