### ISSUE TITLE
Can it support   g install stable  ?

### ISSUE THREAD

**Issue by jan-bar** [voidint/g#127]
As shown in the picture below, I originally wanted to install `go1.21.5`, which should support this requirement.

![image](https://github.com/voidint/g/assets/14202095/835e3ab6-d8e9-4f50-ab67-1456c175cd67)

Since query is available, installation should also be supported.

![image](https://github.com/voidint/g/assets/14202095/e2174e89-4802-42e3-beaa-d15863df6a63)

**Comment by voidint** [comment]
Maybe `latest` should be semantically equivalent to what you mean by `stable`.

**Comment by jan-bar** [comment]
@voidint  Is it possible to design according to the labels on the [official website](https://go.dev/dl/)?.

![image](https://github.com/voidint/g/assets/14202095/4ff265a4-0092-4028-aea1-88ab11bc3c2b)

> Maybe `latest` should be semantically equivalent to what you mean by `stable`.

Indeed, what I want to install is the latest stable version. This needs to be carefully designed.

**Comment by voidint** [comment]
Some [mirror sites](https://mirrors.aliyun.com/golang/) do not have such a label

**Comment by jan-bar** [comment]
GG，It seems that we still have to specify the version honestly.

**Comment by voidint** [comment]
`g install '~1.21'`

**Comment by jan-bar** [comment]
> `g install '~1.21'`

This is also a solution, the specific version should be specified in the project. Most of the time, this kind of installation of the latest stable version is for personal testing. This solution should be enough. Thank you so much
