### ISSUE TITLE
如何在dockerfile中使用？

### ISSUE THREAD

**Issue by seepine** [voidint/g#128]
dockerfile
```
FROM mcr.microsoft.com/devcontainers/base:jammy
USER vscode
SHELL ["/bin/bash", "-c"]
RUN curl -sSL https://raw.githubusercontent.com/voidint/g/master/install.sh | bash && \
  source $HOME/.g/env && g install 1.21 && go install github.com/cosmtrek/air@latest
```
构建镜像运行后air命令无法找到，发现其安装在 `/home/vscode/go/bin/air`

### cat $HOME/.g/env
```
#!/bin/sh
# g shell setup
export GOROOT="${HOME}/.g/go"
export PATH="${HOME}/.g/bin:${GOROOT}/bin:$PATH"
export G_MIRROR=https://golang.google.cn/dl/
```

### cat ~/.bashrc
```
....
# g shell setup
if [ -f "${HOME}/.g/env" ]; then
    . "${HOME}/.g/env"
fi
```

### echo $GOROOT
```
/home/vscode/.g/go
```

**Comment by voidint** [comment]
`go install github.com/cosmtrek/air@latest`就会把二进制文件放在`$GOPATH/bin`目录下，默认也就是`$HOME/go/bin`，这是 go 的行为，不是由 g 决定的。

**Comment by voidint** [comment]
- `GOPATH`环境变量由用户自定义设置会更加合理，你可以在 dockerfile 中加入修改 GOPATH 的相关指令。env 文件中若是设置了默认值，总会有人喜欢有人不喜欢。
- 况且，go 官方在不断地弱化和消除`GOPATH`环境变量的影响。

**Comment by voidint** [comment]
> 是这样，但就我体验而言，对于一个全新环境，通过g安装的go，实际无法做到开箱即用，还是得需要自己配置GOPATH，自己把GOPATH/bin添加到环境变量，而若通过go安装包安装它会去配置这个

抱歉，我理解错你意思了。我会把`$GOPATH/bin`加入到`$HOME/.g/env`文件中去。
