### ISSUE TITLE
Install fails when setting URL with context path to G_MIRROR

### ISSUE THREAD

**Issue by tkyggit** [voidint/g#131]
**Describe the bug/缺陷描述**
Install fails when setting URL with context path to G_MIRROR

**To Reproduce/缺陷复现步骤**
1. set  G_MIRROR with context path url, like https://aaa.com/bbb/dl. context means bbb
2. g ls-remote is fine
3. g install 1.21.0
4. Trying to download from wrong URL　[g] Url "https://aaa.com/dl/go1.21.0.windows-amd64.zip" is unreachable ==> 404

**Expected behavior/期望行为**
expected download url is 'https://aaa.com/bbb/dl', but 'https://aaa.com/dl'
missing context path bbb

**Screenshots/实际运行结果截图**

**Environments (please complete the following information)/运行环境:**
- OS[e.g. uname -a]
  Windows 10
- g -v

    ```shell
1.6.0
    ```

- go env

    ```shell

    ```

- echo $G_EXPERIMENTAL

    ```shell

    ```

- echo $G_HOME

    ```shell

    ```

- echo $G_MIRROR

    ```shell
　　https://aaa.com/bbb/dl
    ```

**Additional context/额外信息**

**Comment by voidint** [comment]
Unable to reproduce the issue. Please follow the steps below:
- Set the `G_MIRROR` environment variable(`export G_MIRROR=https://aaa.com/bbb/dl`)
- Execute command: `g env`
- Execute command: `g install 1.21.0`

**Please provide the complete output of the above commands.**

**Comment by voidint** [comment]
https://github.com/voidint/g/blob/master/collector/official/official_collector.go#L58
