### ISSUE TITLE
g install  error

### ISSUE THREAD

**Issue by hklinux2010** [voidint/g#132]
[g] Url "https://golang.google.cn/dl/" is unreachable ==> Get "https://golang.google.cn/dl/": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2001-04-28T05:04:50+08:00 is before 2024-02-19T08:06:33Z

**Comment by hklinux2010** [comment]
我换上阿里云的那个也是一样的

**Comment by hklinux2010** [comment]
[g] Url "https://mirrors.aliyun.com/golang/" is unreachable ==> Get "https://mirrors.aliyun.com/golang/": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2001-04-28T06:46:36+08:00 is before 2023-10-27T05:56:03Z

**Comment by voidint** [comment]
这是https建立握手建立连接时候的报错，网络问题。你的时间为什么是2001-04-28T05:04:50+08:00？

**Comment by hklinux2010** [comment]
谢谢，刚把时间同步上了，就好使了 非常感谢

**Comment by voidint** [comment]
👌🏻
