### ISSUE TITLE
自定义g命令，使用自定义安装，数据不在自定义命令的目录中

### ISSUE THREAD

**Issue by allmors** [voidint/g#136]
**Describe the bug/缺陷描述**
自定义g命令，使用自定义安装，数据不在自定义命令的目录中 

**To Reproduce/缺陷复现步骤**
1. 修改g命令为自定义的gvm
2. 配置gvm环境变量
3. 使用gvm命令安装go版本
4. 添加环境变量发现go安装在了.g目录（这个目录应该是自动创建的，我创建的为.gvm）
![image](https://github.com/voidint/g/assets/93471589/e29e530f-79de-4476-8684-d3c535780450)

**Expected behavior/期望行为**
我通过mkdir创建一个 *.gvm的目录，使用gvm安装go，应该它也在这个目录

**Screenshots/实际运行结果截图**
结果是使用gvm命令安装go，它不会安装在我自定义的gvm，而是创建新的.g目录进行相关安装
![image](https://github.com/voidint/g/assets/93471589/4f76a032-f948-4daf-a00b-c131351d0123)

**Environments (please complete the following information)/运行环境:**
- window10

- g -v
```
g version 1.6.0
Built:         2023-12-01 21:21:04
Git branch:    master
Git commit:    40a5ad29
Go version:    go1.20.11
OS/Arch:       windows/amd64
Experimental:  false
```
- go env

```
G_HOME=""
G_MIRROR=""
G_EXPERIMENTAL=""
```

**Comment by voidint** [comment]
README中有说明，需要打开以下两个环境变量。
```shell
export G_EXPERIMENTAL=true
export G_HOME=xxx/yyy/zzz/.gvm
```
