### ISSUE TITLE
增加Nginx autoindex采集器

### ISSUE THREAD

**Issue by 863056768** [voidint/g#137]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
增加 [ustc镜像](https://mirrors.ustc.edu.cn/golang/) 的 `Collector`

**Describe alternatives you've considered**

**Additional context**

**Comment by voidint** [comment]
- ustc镜像站点使用的是 Nginx的[ngx_http_autoindex_module](https://nginx.org/en/docs/http/ngx_http_autoindex_module.html)模块，类似情况的镜像站点还有很多，比如[azure.cn](https://mirror.azure.cn/go/)。
