### ISSUE TITLE
Clean 


### ISSUE THREAD

**Issue by Elijah937** [voidint/g#140]
**Describe the bug/缺陷描述**

**To Reproduce/缺陷复现步骤**

**Expected behavior/期望行为**

**Screenshots/实际运行结果截图**

**Environments (please complete the following information)/运行环境:**
- OS[e.g. uname -a]

- g -v

    ```shell

    ```

- go env

    ```shell

    ```

- echo $G_EXPERIMENTAL

    ```shell

    ```

- echo $G_HOME

    ```shell

    ```

- echo $G_MIRROR

    ```shell

    ```

**Additional context/额外信息**

**Comment by voidint** [comment]
???
