### ISSUE TITLE
使用g install 安装提示对方拒绝连接

### ISSUE THREAD

**Issue by Mika-LiFeng** [voidint/g#143]
已经在pwsh上安装成功g，执行安装版本时报错如下
PS C:\Users\mpmf-gmk001> g install 1.22.5
[g] Url "https://go.dev/dl/" is unreachable ==> Get "https://go.dev/dl/": dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it.

在wsl上的ubuntu系统上也安装了g，同样的网络环境下，wsl上ubuntu系统能正常使用g安装go

**Comment by voidint** [comment]
- 网络连接有偶然性，建议重试，或者使用镜像站点；
- 在确保 wsl 内 Linux 网络可用性的前提下，得测试是否 wsl 内**一直不可达**，而 Windows 宿主机**一直可达**，只有这样才能从一定层面证明存在未知bug；
