### ISSUE TITLE
是否应该把".g\bin"加入环境变量?

### ISSUE THREAD

**Issue by Yuelioi** [voidint/g#145]
我发现在ps中可以直接运行, 但是在vscode环境下找不到g命令, 是配置项问题么?

如果直接把 `.g\bin` 加入环境变量, 这样应该都能正常使用了

版本: 1.7
环境: windows

**Comment by voidint** [comment]
README中有相关说明
```shell
$env:GOROOT="$HOME\.g\go"
$env:Path=-join("$HOME\.g\bin;", "$env:GOROOT\bin;", "$env:Path")
```

**Comment by voidint** [comment]
vscode 中的 terminal 是会读取环境变量的，所以将 g 加入到 path 环境变量是推荐的方式。
