### ISSUE TITLE
URL "https://golang.google.cn/dl/" is unreachable ==> Get https://golang.google.cn/dl/: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by yanghao19890607** [voidint/g#16]
这个是什么原因

**Comment by voidint** [comment]
浏览器能正常访问https://golang.google.cn/dl/吗？

**Comment by yanghao19890607** [comment]
> 浏览器能正常访问[https://golang.google.cn/dl/吗？](https://golang.google.cn/dl/%E5%90%97%EF%BC%9F)

找到原因了 alpine 的镜像里面 没装 curl 装上就好了。多谢

**Comment by xx1906** [comment]
也有可能是 dns 的问题
