### ISSUE TITLE
'g update'自我更新

### ISSUE THREAD

**Issue by voidint** [voidint/g#19]
### 如何获取当前可执行程序的绝对路径？
- Linux: `os.Readlink("/proc/self/exe")`
- `exec.LookPath("g")`方式可能并不准确，因为依赖于`PATH`环境变量。

**Comment by Zachary-Zhao** [comment]
filepath.Abs(os.Args[0])

**Comment by voidint** [comment]
> filepath.Abs(os.Args[0])

这个函数是不能满足需求的哦。可以具体看下函数的实现：如果入参不是绝对路径（如`filepath.Abs("bash")`），返回的是`${当前工作目录}/bash`。

**Comment by HaoKunT** [comment]
试试这个包？

[go-update](https://github.com/inconshreveable/go-update)

**Comment by Zerorigin** [comment]
> ### 如何获取当前可执行程序的绝对路径？
> * Linux: `os.Readlink("/proc/self/exe")`
> * `exec.LookPath("g")`方式可能并不准确，因为依赖于`PATH`环境变量。

可通过调用系统原生命令来获取`PATH`环境变量目录里的可执行程序目录绝对路径
For Command (on Windows): `where g`
For Posh (aka Powershell): `Get-Command g | Select-Object -Property "Source" | Format-Wide`
For Linux/Unix: `which g`

**Comment by Zerorigin** [comment]
> 
```
    // 获取执行程序时程序所在目录 - 适用于 go run/build
    if execPath, err = os.Executable(); err != nil {
        log.Println(err)
    }
    execPath, _ = filepath.EvalSymlinks(filepath.Dir(execPath))
```
参考：https://zhuanlan.zhihu.com/p/363714760

**Comment by voidint** [comment]
1.3.0 版本已支持`g update`命令，此issue关闭。
