### ISSUE TITLE
g install 1 安装不成功

### ISSUE THREAD

**Issue by wangzeping722** [voidint/g#27]
运行命令：g install 1 会安装不成功，
`
g install 1

[g] Installation package not found
`
查看官网后发现是因为版本为1不是按照一般的命名规范进行命名。

**Comment by voidint** [comment]
- 其实和版本的命名没有直接关系
- 直接原因是这个版本下确实没有可供`g`去安装的版本，查看下[相关网页](https://golang.google.cn/dl/)可以发现`1`这个版本下只有`go1.4-bootstrap-20170518.tar.gz`和`go1.4-bootstrap-20170531.tar.gz`这两个包。`g`是根据当前操作系统和CPU硬件架构查找对应的包，如`go1.2.2.linux-amd64.tar.gz`，在Linux x86_64环境下就会找这个包。

**Comment by voidint** [comment]
> 所以，其实**1**这个版本可以特殊处理掉吧。

并不打算对这个`1`版本做特殊处理，理由可能有这么几点：
- 提示信息本质上也没有错，的确是找不到安装的包。但是`g ls-remote`输出了版本信息，又没法实际安装，的确不太友好。
- 随着go语言版本的不断更迭，后续可能会再出现类似`1`这样子被`归档`的版本，`特殊处理`不是一个长久之计。
