### ISSUE TITLE
G_MIRROR的问题

### ISSUE THREAD

**Issue by latltt** [voidint/g#28]
设置了G_MIRROR  https://golang.google.cn/dl/   后，是可以正常查询，但是下载还是从官方地址下载，造成无法正常install。
出错信息：
[g] Installation package(https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz) download failed ==> local error: tls: bad record MAC

**Comment by voidint** [comment]
> 设置了G_MIRROR https://golang.google.cn/dl/ 后，是可以正常查询，但是下载还是从官方地址下载，造成无法正常install。
> 出错信息：
> [g] Installation package(https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz) download failed ==> local error: tls: bad record MAC

是手动调用的，还是放在脚本中自动化调用？直观的感觉，是调用`g install`时环境变量`G_MIRROR`被有意无意地清空了，排查下是不是这种情况。

**Comment by latltt** [comment]
我今天开机再试了下，install也正常了。不知是怎么回事，我昨晚也是手动调用的。刚g ls-remote都正常显示所有版本。之后g install 1.14.1就报错了。

**Comment by voidint** [comment]
- 国内的镜像站点和官网使用的下载地址的域名都是`dl.google.com`，所以这个问题和环境变量`G_MIRROR`的设置没有关系。
- 拿`tls: bad record MAC`作为关键字去搜索，也能搜到一些，一般是说和网络环境有关，碰到这种情况建议就是重试下。
- https://medium.com/geopits/local-error-tls-bad-record-mac-50ca14a6a658
- https://github.com/microsoft/WSL/issues/4306
