### ISSUE TITLE
不支持ARM架构

### ISSUE THREAD

**Issue by HaoKunT** [voidint/g#29]
尝试了下在树莓派上用这个工具，遇到的一个问题，`install`的时候，下载的不是ARM版本的，执行go的时候报错
``` shell
pi@raspberrypi:~ $ go version
-bash: /home/pi/.g/go/bin/go: cannot execute binary file: Exec format error
```
我是在Windows上交叉编译了`g`的源码，然后上传到树莓派上

**Comment by voidint** [comment]
- 您是在Windows环境交叉编译的g，通过`g install`安装的某个go版本，但是安装完的go运行错误，是这个意思吗？
- 非常感谢您的反馈，能否提供下这些线索：1、go env的输出。2、g install安装的是具体哪个版本。3、再次执行g install能否重现之前的问题。

**Comment by HaoKunT** [comment]
- 是的，我是交叉编译的g，然后将二进制传到树莓派上

具体描述：

传输后，将`g`二进制放到`/usr/local/bin`下，`g`命令可成功执行，且可正常的执行`g install <version>`，输出`Installed successfully`，并且此时执行`g ls`可正常显示所安装的相应版本

问题：

安装后执行`go version`（或者go的其他命令），均报错，具体内容见上述。

环境：
- `go env`：由于go执行不了所以没有`go env`的输出
- `g install`安装1.14.2版本，1.13.10版本均有此问题
- 卸载可正常卸载，重新安装后依然如此
- 交叉编译的命令`GOOS=linux GOARCH=arm GOARM=7 go build -ldflags "-s -w"`
- `g`用的master分支，直接clone的，对应的版本是1.1.1

我怀疑下载的是amd64的架构的包，但是我看了源码，指定了对应的arch和os，就不是很清楚具体是哪的问题

**Comment by voidint** [comment]
我怀疑的是树莓派上应该安装的是`go1.14.2.linux-armv6l.tar.gz`这个包，实际安装的是`go1.14.2.linux-arm64.tar.gz`。能否手工下载下这两个包分别验证下？


![Jietu20200503-101001](https://user-images.githubusercontent.com/6327183/80896943-51de0580-8d26-11ea-9a7c-09fb49be58fd.jpg)

**Comment by voidint** [comment]
另外，`~/.g/downloads`目录下存放的是通过g下载的go安装包，文件名是按照GOOS、GOARCH进行命名的。那么，实际这个目录下的安装包文件名是什么呢？

**Comment by HaoKunT** [comment]
- `~/.g/downloads`目录下的安装包文件名为`go1.14.2.linux-arm.tar.gz`，我算了SHA256，确实下载的是`go1.14.2.linux-arm64.tar.gz`这个包。
- `uname -a`的输出
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.35-v7+ #1314 SMP Fri May 1 17:41:46 BST 2020 armv7l GNU/Linux
```

**Comment by voidint** [comment]
- 所以，直接原因就是这样：GOOS=linux，GOARCH=arm，能匹配到的安装包是`go1.14.2.linux-arm64.tar.gz`和`go1.14.2.linux-armv6l.tar.gz`，由于前者位置靠前，所以被优先匹配到了，而树莓派上实际应该安装后者。
- 要解决类似的问题，可能得引入这样的机制：如果程序不能唯一确定一个安装包，就把选择权交给用户，由用户二次确认安装包。

**Comment by HaoKunT** [comment]
也许要一个类似nodejs的`inquirer.js`的列表，命令行那里自己撸一个？

**Comment by voidint** [comment]
- 新增一个方法，找出所有匹配的package。
```go
// FindPackages 返回指定操作系统和硬件架构的版本包
func (v *Version) FindPackages(kind, goos, goarch string) (pkgs []*Package, err error) {
	prefix := fmt.Sprintf("go%s.%s-%s", v.Name, goos, goarch)
	for i := range v.Packages {
		if v.Packages[i] == nil || !strings.EqualFold(v.Packages[i].Kind, kind) || !strings.HasPrefix(v.Packages[i].FileName, prefix) {
			continue
		}
		pkgs = append(pkgs, v.Packages[i])
	}
	if len(pkgs) == 0 {
		return nil, ErrPackageNotFound
	}
	return pkgs, nil
}
```

- 调用侧判断返回的package数量，多于一个则有用户选择安装哪个package。
