### ISSUE TITLE
 Access is denied.

### ISSUE THREAD

**Issue by windyear** [voidint/g#31]
1. 安装go的时候出现重命名的Access is denied 错误。
2. 错误信息如下：
`[g] Rename C:\Users\username\.g\versions\go C:\Users\username\.g\versions\1.12: Access is denied.
`
请问是什么原因造成的，试过用管理员方式打开powershell
@voidint

**Comment by voidint** [comment]
> 1. 安装go的时候出现重命名的Access is denied 错误。
> 2. 错误信息如下：
>    `[g] Rename C:\Users\username\.g\versions\go C:\Users\username\.g\versions\1.12: Access is denied. `
>    请问是什么原因造成的，试过用管理员方式打开powershell
>    @voidint

- 不知道你用的是哪个版本的Windows，我在Windows server 2012上测试了一下，只要取消当前用户或者所属用户组的相关目录写权限，就会出现`Access is denied`的错误。
- 建议你查看下`.g/version`目录及其父目录，看看是否有哪一层的目录的写权限被取消了。
![image](https://user-images.githubusercontent.com/6327183/84138765-6af27880-aa81-11ea-9a2d-aed53749447a.png)

**Comment by windyear** [comment]
以解决，是因为i最上层目录没有写权限造成的，感谢
