### ISSUE TITLE
[g] Installation package(/dl/go1.14.4.darwin-amd64.tar.gz) download failed ==> Get "/dl/go1.14.4.darwin-amd64.tar.gz": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by yoloyi** [voidint/g#33]
g version 1.1.2
build: 2020-05-05T15:23:28+08:00
branch: master
commit: c243baa758cf114bfff33cf703ef424887001abf

```bash
$ echo $G_MIRROR;
https://golang.google.cn/dl/
 $ g install 1.14.4 
[g] Installation package(/dl/go1.14.4.darwin-amd64.tar.gz) download failed ==> Get "/dl/go1.14.4.darwin-amd64.tar.gz": unsupported protocol scheme ""
```

Hi  
一直 install 都报这个错误，但是可以通过 g  ls-remote 看到这个版本，报错信息如上 *unsupported protocol scheme*

**Comment by voidint** [comment]
macos 64位的机器是吧？

**Comment by voidint** [comment]
![image](https://user-images.githubusercontent.com/6327183/86421883-0fc54600-bd0e-11ea-810f-edebdb508735.png)
- 原因就是网站调整了，下载地址从绝对路径改成了相对路径。
- 我会去适配下。

**Comment by voidint** [comment]
- 我已经修复了，可以重新拉取下master分支并编译g。
- 晚些时候我会release一个补丁版本1.1.3。

**Comment by yoloyi** [comment]
好的。谢谢
