### ISSUE TITLE
怎么自定义 g 安装目录 .我想自定义到 D 盘. 

### ISSUE THREAD

**Issue by DestinyHunter** [voidint/g#34]
rt

**Comment by voidint** [comment]
详见https://github.com/voidint/g/issues/18

**Comment by DestinyHunter** [comment]
win 上 没有生效, 设置 G_HOME 到 D:\UserPath\GoLang 没有生效, 依然安装到 c:/user/.go

**Comment by voidint** [comment]
😂这还是个待实现的特性，如果已经实现了issue也就关掉了。

**Comment by zaunist** [comment]
这个不能识别电脑上已经安装的 go 版本

**Comment by voidint** [comment]
> 这个不能识别电脑上已经安装的 go 版本

不是通过g安装的，都识别不了。

**Comment by voidint** [comment]
- windows系统下`G_HOME`环境变量已经生效，可以拉取master分支代码尝试下。
- 切换到自定义的目录后，需要手工修改`G_HOME`、`GOROOT`、`Path`等环境变量。建议按照下图示例的方式修改，好处是即使今后再次变更目录，也只需要修改`G_HOME`一个环境变量。
![image](https://user-images.githubusercontent.com/6327183/91656008-bd26c100-eae7-11ea-9ca9-c07df015c29a.png)

**Comment by cf313995** [comment]
1.2.0版本已经实现自定义盘符了么？

**Comment by voidint** [comment]
> 1.2.0版本已经实现自定义盘符了么？

1.2.0并不支持。master分支上的版本对Windows平台有初步的支持，只是还未release。如果你用的Windows，可以尝试下。

**Comment by cf313995** [comment]
> > 1.2.0版本已经实现自定义盘符了么？
> 
> 1.2.0并不支持。master分支上的版本对Windows平台有初步的支持，只是还未release。如果你用的Windows，可以尝试下。

好的

**Comment by chawyehsu** [comment]
> > 1.2.0版本已经实现自定义盘符了么？
> 
> 1.2.0并不支持。master分支上的版本对Windows平台有初步的支持，只是还未release。如果你用的Windows，可以尝试下。

有没有计划发个版？我这边准备支持 Scoop 安装，有 `G_HOME` 可以更 portable。

**Comment by voidint** [comment]
> > > 1.2.0版本已经实现自定义盘符了么？
> > 
> > 
> > 1.2.0并不支持。master分支上的版本对Windows平台有初步的支持，只是还未release。如果你用的Windows，可以尝试下。
> 
> 有没有计划发个版？我这边准备支持 Scoop 安装，有 `G_HOME` 可以更 portable。

master分支中引入了新的环境变量`G_EXPERIMENTAL`来开启这类实验特性，详见 #18 的最新评论内容。
