### ISSUE TITLE
不能检测使用windows安装包安装的go版本吗

### ISSUE THREAD

**Issue by ayuayue** [voidint/g#37]
使用`go`的`windows`安装器安装了1.15,但是 `g ls` 没有检测到.是否与`windows`安装器不兼容.二者只能取一?

**Comment by voidint** [comment]
不是通过`g`安装的，就不会识别到。

**Comment by ayuayue** [comment]
那两个方式安装的可以共存吗

**Comment by ayuayue** [comment]
`ls remote` 时出现问题
```
[g] URL "https://golang.org/dl/" is unreachable ==> Get "https://golang.org/dl/": dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

终端 `curl -v https://google.com ` 可以响应,浏览器那个网站也可以访问.包括 choco 都可以正常使用.只这个提示连接问题.

**Comment by ayuayue** [comment]
```
 curl -v https://golang.org/dl/
```
```
详细信息: GET https://golang.org/dl/ with 0-byte payload
详细信息: received -1-byte response of content type text/html; charset=utf-8


StatusCode        : 200
StatusDescription : OK
Content           :
                    <!DOCTYPE html>
                    <html lang="en">
                    <meta charset="utf-8">
                    <meta name="description" content="Go is an open source programming language that makes it easy to build simple, reliabl
                    e, and efficient softwar...
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Vary: Accept-Encoding
                    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
                    Alt-Svc: h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=259200...
Forms             : {}
Headers           : {[Transfer-Encoding, chunked], [Vary, Accept-Encoding], [Strict-Transport-Security, max-age=31536000; includeSubDomains
                    ; preload], [Alt-Svc, h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2
                    592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,
                    43"]...}
Images            : {@{innerHTML=; innerText=; outerHTML=<IMG class=Header-logo alt=Go src="/lib/godoc/images/go-logo-blue.svg">; outerText
                    =; tagName=IMG; class=Header-logo; alt=Go; src=/lib/godoc/images/go-logo-blue.svg}, @{innerHTML=; innerText=; outerHTML
                    =<IMG class=Footer-gopher alt="The Go Gopher" src="/lib/godoc/images/footer-gopher.jpg">; outerText=; tagName=IMG; clas
                    s=Footer-gopher; alt=The Go Gopher; src=/lib/godoc/images/footer-gopher.jpg}}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<INPUT spellcheck=false aria-label=Search class=HeaderSearch-input name=q required
                     autocorrect="off" autocomplete="off" autocapitalize="off" placeholder="Search">; outerText=; tagName=INPUT; spellcheck
                    =false; aria-label=Search; class=HeaderSearch-input; name=q; required=; autocorrect=off; autocomplete=off; autocapitali
                    ze=off; placeholder=Search}}
Links             : {@{innerHTML=Support the Equal Justice Initiative.; innerText=Support the Equal Justice Initiative.; outerHTML=<A href=
                    "https://support.eji.org/give/153413/#!/donation/checkout" rel=noopener target=_blank>Support the Equal Justice Initiat
                    ive.</A>; outerText=Support the Equal Justice Initiative.; tagName=A; href=https://support.eji.org/give/153413/#!/donat
                    ion/checkout; rel=noopener; target=_blank}, @{innerHTML=<IMG class=Header-logo alt=Go src="/lib/godoc/images/go-logo-bl
                    ue.svg">; innerText=; outerHTML=<A href="/"><IMG class=Header-logo alt=Go src="/lib/godoc/images/go-logo-blue.svg"></A>
                    ; outerText=; tagName=A; href=/}, @{innerHTML=Documents; innerText=Documents; outerHTML=<A href="/doc/">Documents</A>;
                    outerText=Documents; tagName=A; href=/doc/}, @{innerHTML=Packages; innerText=Packages; outerHTML=<A href="/pkg/">Packag
                    es</A>; outerText=Packages; tagName=A; href=/pkg/}...}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 527819
```

**Comment by voidint** [comment]
> `ls remote` 时出现问题
> 
> ```
> [g] URL "https://golang.org/dl/" is unreachable ==> Get "https://golang.org/dl/": dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> ```
> 
> 终端 `curl -v https://google.com ` 可以响应,浏览器那个网站也可以访问.包括 choco 都可以正常使用.只这个提示连接问题.

设置环境变量`G_MIRROR=https://golang.google.cn/dl/`

**Comment by ayuayue** [comment]
可以了,多谢

**Comment by voidint** [comment]
> ```
>  curl -v https://golang.org/dl/
> ```
> 
> ```
> 详细信息: GET https://golang.org/dl/ with 0-byte payload
> 详细信息: received -1-byte response of content type text/html; charset=utf-8
> 
> 
> StatusCode        : 200
> StatusDescription : OK
> Content           :
>                     <!DOCTYPE html>
>                     <html lang="en">
>                     <meta charset="utf-8">
>                     <meta name="description" content="Go is an open source programming language that makes it easy to build simple, reliabl
>                     e, and efficient softwar...
> RawContent        : HTTP/1.1 200 OK
>                     Transfer-Encoding: chunked
>                     Vary: Accept-Encoding
>                     Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
>                     Alt-Svc: h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=259200...
> Forms             : {}
> Headers           : {[Transfer-Encoding, chunked], [Vary, Accept-Encoding], [Strict-Transport-Security, max-age=31536000; includeSubDomains
>                     ; preload], [Alt-Svc, h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2
>                     592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,
>                     43"]...}
> Images            : {@{innerHTML=; innerText=; outerHTML=<IMG class=Header-logo alt=Go src="/lib/godoc/images/go-logo-blue.svg">; outerText
>                     =; tagName=IMG; class=Header-logo; alt=Go; src=/lib/godoc/images/go-logo-blue.svg}, @{innerHTML=; innerText=; outerHTML
>                     =<IMG class=Footer-gopher alt="The Go Gopher" src="/lib/godoc/images/footer-gopher.jpg">; outerText=; tagName=IMG; clas
>                     s=Footer-gopher; alt=The Go Gopher; src=/lib/godoc/images/footer-gopher.jpg}}
> InputFields       : {@{innerHTML=; innerText=; outerHTML=<INPUT spellcheck=false aria-label=Search class=HeaderSearch-input name=q required
>                      autocorrect="off" autocomplete="off" autocapitalize="off" placeholder="Search">; outerText=; tagName=INPUT; spellcheck
>                     =false; aria-label=Search; class=HeaderSearch-input; name=q; required=; autocorrect=off; autocomplete=off; autocapitali
>                     ze=off; placeholder=Search}}
> Links             : {@{innerHTML=Support the Equal Justice Initiative.; innerText=Support the Equal Justice Initiative.; outerHTML=<A href=
>                     "https://support.eji.org/give/153413/#!/donation/checkout" rel=noopener target=_blank>Support the Equal Justice Initiat
>                     ive.</A>; outerText=Support the Equal Justice Initiative.; tagName=A; href=https://support.eji.org/give/153413/#!/donat
>                     ion/checkout; rel=noopener; target=_blank}, @{innerHTML=<IMG class=Header-logo alt=Go src="/lib/godoc/images/go-logo-bl
>                     ue.svg">; innerText=; outerHTML=<A href="/"><IMG class=Header-logo alt=Go src="/lib/godoc/images/go-logo-blue.svg"></A>
>                     ; outerText=; tagName=A; href=/}, @{innerHTML=Documents; innerText=Documents; outerHTML=<A href="/doc/">Documents</A>;
>                     outerText=Documents; tagName=A; href=/doc/}, @{innerHTML=Packages; innerText=Packages; outerHTML=<A href="/pkg/">Packag
>                     es</A>; outerText=Packages; tagName=A; href=/pkg/}...}
> ParsedHtml        : mshtml.HTMLDocumentClass
> RawContentLength  : 527819
> ```

你应该设置了HTTP_PROXY、HTTPS_PROXY的网络代理，所以curl能通。`g`并没有支持这两个环境变量，所以暂时通不了。
