### ISSUE TITLE
不同版本的go的gopath

### ISSUE THREAD

**Issue by TrueAbc** [voidint/g#44]
想问下大佬支持多gopath的管理吗, 我使用的go1.14的protobuf的插件是安装在gopath的bin目录下的, 然后我是直接将这个gopath的bin目录添加到了PATH下,  这样相当于切换不同的go版本如果需要gopath的相关工具都需要手动指定。想问下g可以进行相关的管理吗

**Comment by voidint** [comment]
不知道[direnv](https://github.com/direnv/direnv)能不能满足你的需求？切换到目标目录后读取目录下的`.envrc`文件中的环境变量。
