### ISSUE TITLE
m1 版本的go无法安装

### ISSUE THREAD

**Issue by MikyChow** [voidint/g#45]
你好，目前ls-remote只能列出版本号，但是没有架构名称。 如果是直接安装16.2则为amd64的，希望能支持选择架构安装

**Comment by voidint** [comment]
> 你好，目前ls-remote只能列出版本号，但是没有架构名称。 如果是直接安装16.2则为amd64的，希望能支持选择架构安装

感谢你的反馈。由于我手头没有m1的电脑没法直接测试，只能做简单地推测：按照你的说法，预期应该安装的是arm64版本，实际安装的是amd64版本。由于硬件架构的选择依据是`runtime.GOARCH`，因此只能认为该常量的值就是`amd64`，程序才会自动下载该硬件架构的包。总结起来，我怀疑你运行的`g`程序并不是原生的arm架构，而是通过`rosetta`程序转换的。如果真是这样，那么请下载[arm64版本的g](https://github.com/voidint/g/releases/download/v1.2.0/g1.2.0.darwin-arm64.tar.gz)后再尝试安装（g install 1.16.2）。注意：m1仅能安装go1.16及以上的版本。

**Comment by voidint** [comment]
问题解决了吗？

**Comment by MikyChow** [comment]
来迟了，解决了。 应该就是你说的问题。
我重新下载了g的arm版本就可以了
