### ISSUE TITLE
独立 gopath/bin

### ISSUE THREAD

**Issue by ercJuL** [voidint/g#50]
部分 go 相关工具会生成 bin 文件，要向其它语言一样隔离各个环境最好 gopath/bin 也能隔离，gopath/bin 也用软链接，只是更新链接后，新环境并不会自动编译，也许可以按 pipenv 的思路按工程生成 gopath，只是因为最后链接到同一个位置，同时打开多个工程会相互干扰

**Comment by voidint** [comment]
- 不是太理解你的意思，请再详细描述下，最好举个例子。
- GOPATH已经进入生命的倒计时，现阶段针对GOPATH相关的功能开发大概率存在方向上的问题。
