### ISSUE TITLE
Goland debug 异常

### ISSUE THREAD

**Issue by chenhl05** [voidint/g#58]
Hi~，我通过g的方式去安装的Go，然后在Goalnd debug程序的时候，窗口显示是：Frame is not available。然后我卸载g已经环境变量之后，用go官方的exe安装包，同样的程序，同样的位置debug的时候，能够正常暂停，并显示变量。
不知道有没有遇到过这样的情况呢？

**Comment by voidint** [comment]
我没有太多Windows下goland的使用经验，无法提供有效的建议。直觉上我能给出的建议是：
- 重启goland，如果goland版本较低，建议升级。
- 查看goland设置中Go相关的环境变量是否设置正确。

**Comment by chenhl05** [comment]
好的~感谢
