### ISSUE TITLE
无法下载golang1.15版本

### ISSUE THREAD

**Issue by hxcGit** [voidint/g#61]
【问题】：
`$  g install 1.15  `
[g] Installation package not found

查看了 #41 和 #33，推荐更新voidint/g版本

请问如何更新该软件呢？有脚本可以一键更新吗；还是需要卸载软件后重新安装新版本；（之前已经按照的golang version会收到影响吗）

感谢您提供的软件

**Comment by hxcGit** [comment]
补充说明一下
![image](https://user-images.githubusercontent.com/60642406/157813298-b8483d06-90cd-4d69-9537-165c746a296a.png)
g版本是1.2.1
机器是macos arm64

**Comment by voidint** [comment]
直接原因是 go1.15 并不原生支持 M1 芯片的 macOS 系统。建议安装 go1.16 及以上版本。

**Comment by voidint** [comment]
go官方未提供 M1 芯片对应的安装包，因此 g 无法安装 go1.15。
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/6327183/157827485-ccf88c53-c5e3-45e4-a0e8-9ebf5729b830.png">

**Comment by hxcGit** [comment]
收到，非常感谢您的回复。
