### ISSUE TITLE
macos 安装1.18.1 的时候提示[g] Installation package not found

### ISSUE THREAD

**Issue by waini1110** [voidint/g#63]
macos 安装1.18.1 的时候提示[g] Installation package not found

但是1.18 是没问题的

**Comment by waini1110** [comment]
额，我知道原因了，原来是官网并没有发布macos的1.18.1 版本。。。

**Comment by voidint** [comment]
是的，我今天上午也发现这个问题了。不知道是go官方疏忽大意忘记发布macOS系统相关的包，还是macOS系统下还有什么无法解决的大bug，反正截止目前还没有针对macOS的包释出。

**Comment by waini1110** [comment]
> 是的，我今天上午也发现这个问题了。不知道是go官方疏忽大意忘记发布macOS系统相关的包，还是macOS系统下还有什么无法解决的大bug，反正截止目前还没有针对macOS的包释出。

但是很奇怪，homebrew 里面有1.18.1的包。。。

**Comment by voidint** [comment]
homebrew应该是通过源代码编译的

**Comment by voidint** [comment]
macOS下1.18.1官方包已经出来了，可以用g安装了。
