### ISSUE TITLE
Win10 Goland无法将GOROOT添加到配置里面

### ISSUE THREAD

**Issue by xiaoxinpro** [voidint/g#66]
![image](https://user-images.githubusercontent.com/11443745/168995120-c08c7367-4618-4576-a78c-5c449cfd72e4.png)

```
go version go1.18.2 windows/amd64

g version 1.3.0
build: 2022-04-03T21:47:11+08:00
branch: master
commit: d027d1c2015ebb6f3465cd4160976c1f9c8c7a6b
```

**Comment by voidint** [comment]
goland是哪个版本呢？

**Comment by xiaoxinpro** [comment]
> goland是哪个版本呢？

2020.01

**Comment by voidint** [comment]
这是 g 在 Windows 下创建软链接的方式。建议你删除目录后重新安装一个 Go SDK，或者自己执行命令行工具 mklink 去创建一个目录联接，测试下goland是否能识别到。

```go
func mkSymlink(oldname, newname string) (err error) {
	if runtime.GOOS == "windows" {
		// Windows 10下无特权用户无法创建符号链接，优先调用mklink /j创建'目录联接'
		if err = exec.Command("cmd", "/c", "mklink", "/j", newname, oldname).Run(); err == nil {
			return nil
		}
	}
	return os.Symlink(oldname, newname)
}
```

**Comment by xiaoxinpro** [comment]
是Goland的问题，使用最新版本的Goland问题解决。

**Comment by scopeccsky** [comment]
同样的问题，用windows 11 打开wsl的.g找不到。
已经在  运行->管理目标中添加了 go可执行文件的位置

**Comment by voidint** [comment]
> 同样的问题，用windows 11 打开wsl的.g找不到。 已经在 运行->管理目标中添加了 go可执行文件的位置

WSL 属于Linux系统，在它下面安装的 g 和 go 都是Linux平台的软件，用Windows下的软件去找怎么会找得到？两个操作系统的二进制程序不兼容。

**Comment by scopeccsky** [comment]
> > 同样的问题，用windows 11 打开wsl的.g找不到。 已经在 运行->管理目标中添加了 go可执行文件的位置
> 
> WSL 属于Linux系统，在它下面安装的 g 和 go 都是Linux平台的软件，用Windows下的软件去找怎么会找得到？两个操作系统的二进制程序不兼容。

确定了是windows无法识别wsl的软连接的问题， 其实在wsl和windows的二进制是可以互相运行的， 在wsl 使用g.exe 是可以的

**Comment by voidint** [comment]
> > > 同样的问题，用windows 11 打开wsl的.g找不到。 已经在 运行->管理目标中添加了 go可执行文件的位置
> > 
> > 
> > WSL 属于Linux系统，在它下面安装的 g 和 go 都是Linux平台的软件，用Windows下的软件去找怎么会找得到？两个操作系统的二进制程序不兼容。
> 
> 确定了是windows无法识别wsl的软连接的问题， 其实在wsl和windows的二进制是可以互相运行的， 在wsl 使用g.exe 是可以的

Linux 是无法直接运行 .exe 可执行文件的，否则就没有必要开发 wine 之类的软件了，人们也不会抱怨 Linux 下没有QQ、微信、迅雷、爱奇艺等各种软件了。
