### ISSUE TITLE
1.3.0版本不能自定义go的路径

### ISSUE THREAD

**Issue by Facker007** [voidint/g#68]
<img width="408" alt="q-1" src="https://user-images.githubusercontent.com/42063107/171107623-dca7dd7b-bc86-4435-9f2a-77b046f31a5e.png">
设置了后，还是不能自定义路径。
还是会安装在c盘的用户下

**Comment by Facker007** [comment]
[](url
<img width="458" alt="q2" src="https://user-images.githubusercontent.com/42063107/171108070-7eee696f-5147-4c1c-a2dd-0e5671dd931f.png">
)

**Comment by voidint** [comment]
https://github.com/voidint/g/issues/18#issuecomment-754010792 需要设置环境变量`G_EXPERIMENTAL=true`开启实验特性

**Comment by Facker007** [comment]
噢噢，可以了。非常谢谢你的帮助。
生活愉快，天天开心了！！！
