### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by xidian237** [voidint/g#72]
win10系统
g install 时报错 Access is denied，权限都check过了，没有问题，
![image](https://user-images.githubusercontent.com/17851643/180940513-f8077dd7-dee4-4492-974c-3ef256618343.png)
而且我在本地调用os.Rename()接口，也可以修改成功
![image](https://user-images.githubusercontent.com/17851643/180940761-c7642cd2-ce76-4c5b-bbb5-d0d1777d71eb.png)

**Comment by xidian237** [comment]
我也试了用源码，有时候可以rename成功，有时候不行

**Comment by voidint** [comment]
检查下你的`c:\goversions`目录权限，是不是有什么限制。再试试看非系统盘。

**Comment by jianghairui** [comment]
我也遇到一样的问题了, 把本地防火墙关了, 杀毒软件关了就好了
系统 win11专业版
