### ISSUE TITLE
macbook 无法安装 go1.15

### ISSUE THREAD

**Issue by lwwgo** [voidint/g#73]
g install 1.15
报错：[g] Installation package not found
g 版本：1.4.0
            g version 1.4.0
            build: 2022-06-08T21:28:54+08:00
            branch: master
            commit: e1fdf711f3175765997863f71ab5632ea5cf4261

**Comment by voidint** [comment]
go从1.16版本开始才原生支持ARM处理器的macOS系统

**Comment by lwwgo** [comment]
嗯嗯，感谢回复。
对了，在linux下，用g安装go 1.15
g install 1.15
g use 1.15
go version，报如下错误
-bash：No such file or directory /home/work/.g/go/bin/go
已经手动检查了， /home/work/.g/go/bin/go在

**Comment by voidint** [comment]
`-bash：No such file or directory /home/work/.g/go/bin/go`这类报错信息一般是两种原因：1、go不是可执行文件。2、没有把父级的`bin`目录加入到 PATH 环境变量中。基本上是后一种原因。
