### ISSUE TITLE
w11的go version就是不生效

### ISSUE THREAD

**Issue by Fajar-w** [voidint/g#75]
![image](https://user-images.githubusercontent.com/24646605/187193601-f332c387-38af-46be-ac63-ee1273822270.png)
切换然后go version
![image](https://user-images.githubusercontent.com/24646605/187193794-439a28c3-e846-4d11-aac6-bb96fc9e6a7b.png)
path的环境变量
![image](https://user-images.githubusercontent.com/24646605/187193899-fa661255-a429-4959-88ad-ad68bb1bb48a.png)

**Comment by voidint** [comment]
很明显，你的`PATH`环境变量设置错了。起码应该把`D:\exe\g\golang\.g\go\bin`加入`PATH`。

**Comment by Fajar-w** [comment]
> 很明显，你的`PATH`环境变量设置错了。起码应该把`D:\exe\g\golang\.g\go\bin`加入`PATH`。

GOROOT = D:\exe\g\golang\.g\go
%GOROOT%\bin 不是   D:\exe\g\golang\.g\go\bin的意思 ？？

**Comment by voidint** [comment]
这截图我算是看明白了：使用g切换了新的版本，但是`go version`的输出依然是切换前的版本。最可能的就是path中包含了之前安装的其他go版本，并且它的查找优先级更高。建议你通过类似 Unix/Linux 下的`which`命令查找下`go`可执行文件的指向路径。这种应该不难排查。
