### ISSUE TITLE
go: cannot find GOROOT directory: D:\Program Files\g\go

### ISSUE THREAD

**Issue by 9aceh** [voidint/g#76]
**Describe the bug/缺陷描述**
成功安装g和配置好环境变量后使用任何go命令都说找不到GOROOT目录

**To Reproduce/缺陷复现步骤**
1. 环境变量截图
![1663596070872](https://user-images.githubusercontent.com/38652138/191035960-6e9d6907-5b74-4107-b408-16a36c68806f.png)
path：
![1663596251752](https://user-images.githubusercontent.com/38652138/191036158-32dba6e3-3fc0-4327-bc7a-2773095e0888.png)
2. g和go正常
![image](https://user-images.githubusercontent.com/38652138/191036565-963e6463-4da6-46ef-b7b8-3bbfcb86ef43.png)
3. See error 但是go加上任何参数都会找不到GOROOT目录
![1663596509396](https://user-images.githubusercontent.com/38652138/191037095-c613efd6-29f2-41f4-adca-575e84d41860.png)

**Expected behavior/期望行为**
能够正常使用go

**Comment by voidint** [comment]
- 你的环境变量设置是符合预期的，我没有Windows的环境，不方便去复现。
- 使用类似 Unix 系统下的`which go`命令确认下二进制文件 go 是否指向`D:\Program Files\g\go\bin\go`。
- 我建议你安装一个高版本（目前安装的`1.4.3`太低了），以此来判断是否是版本较低的原因。
- 安装一个高版本后，执行下`go env GOROOT`，看看输出。
- 或者尝试下不包含空格 GOROOT 路径。

**Comment by voidint** [comment]
- 建议你切换到`D:\Program Files\g\go\bin`目录下，使用这个目录下的 go 二进制程序执行下`go version`。如果执行结果依然是报错，那么就是go这个版本本身的问题，如果正常输出，那么一定是你配置上的问题，环境变量未生效或者设置错误。

**Comment by 9aceh** [comment]
感谢您的回复，我安装了个1.19.1版本的go，输出正常了

**Comment by voidint** [comment]
好的
