### ISSUE TITLE
支持安装本地已经下载好的安装包吗？

### ISSUE THREAD

**Issue by f2xb** [voidint/g#79]

**Comment by voidint** [comment]
可以，但需要满足一定条件。`~/.g/downloads`是下载缓存目录，如果手动下载了安装包（仅限`tar.gz`和`zip`），那么将安装包放入此目录，并且文件名与官方命名保持一致，那么在执行`g install`时就会跳过下载步骤，计算安装包的 SHA256 ，若一致就会直接解压安装。
