### ISSUE TITLE
/usr/bin/ld: /tmp/go-link-3026352441/000008.o(.text+0x74): unresolvable 

### ISSUE THREAD

**Issue by goctl** [voidint/g#81]
**Describe the bug/缺陷描述**
/data/.g/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-3026352441/000008.o(.text+0x74): unresolvable H��@�>H���FH��H��H��@�~�F�H��@�~H��8�H��H��0�FH��H��(�FH��H�� �FH��H���FH��H���FH��H���F�fD relocation against symbol `stderr@@GLIBC_2.2.5'
/usr/bin/ld: BFD version 2.20.51.0.2-5.48.el6_10.1 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: ld returned 1 exit status

**To Reproduce/缺陷复现步骤**
1. centos6.10环境
2. 更新了yum库也不起作用
3. go version go1.17.13 linux/amd64
4. yum install binutils 已经是最新 Package binutils-2.20.51.0.2-5.48.el6_10.1.x86_64 already installed and latest version
5. go test -race ./...

**Expected behavior/期望行为**
希望能build成功

**Screenshots/实际运行结果截图**
![image](https://user-images.githubusercontent.com/7391627/203718917-bf55db82-fbb4-4ece-a931-8877eb279f14.png)

**Environments (please complete the following information)/运行环境:**
- OS[e.g. uname -a]
    ```shell
       centos6.10  
       Linux test02.novalocal 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 
    ```GNU/Linux
- g --version
    ```shell
      1.4.0
    ```
- go env
    ```shell
     go1.17.13 linux/amd64
    ```

**Comment by goctl** [comment]
I have fixed the bug.
原因：binutils版本太低，centos6下yum源最高也只能安装binutils-2.20
解决版本：手动升级binutils到2.29（尝试了一下2.26不行，还太低。）
`
wget http://ftp.gnu.org/gnu/binutils/binutils-2.29.tar.bz2
tar -xjf binutils-2.29.tar.bz2
cd binutils-2.29
./configure  --prefix=/usr
make && make install
ld -v
`

**Comment by voidint** [comment]
看截图这不是在编译，是跑单元测试。如果去掉`-race`选项，那就可以不依赖于 cgo ：`CGO_ENABLED=0 go test -v ./...`。
