### ISSUE TITLE
Win10 安装后提示 go: command not found

### ISSUE THREAD

**Issue by mhtshhp** [voidint/g#84]
Win10 使用 MobaXterm、CMD、Powershell都安装过一次，提示安装成功，但是运行go version，提示 go: command not found

以下是命令和返回的内容：

> g ls
* 1.18.9

> g install 1.18.9
[g] "1.18.9" version has been installed.

> g use 1.18.9
go version go1.18.9 windows/amd64

> go version
go: command not found

想了解下g install 安装到了哪里？是不是下载的目录需要加入到全局path里？

![微信截图_20230105195101](https://user-images.githubusercontent.com/12815050/210774117-ca48b049-8f54-4869-b8b8-873f288ab1ad.png)

**Comment by voidint** [comment]
`g`的默认路径是用户家目录下的`.g`目录，此目录下的结构类似这样：
```shell
~ tree -L 2 ~/.g
/Users/voidint/.g
├── bin
│   └── g
├── downloads
│   ├── g1.5.0.darwin-arm64.tar.gz
│   ├── go1.18.9.darwin-arm64.tar.gz
│   ├── go1.19.4.darwin-arm64.tar.gz
│   ├── go1.20rc1.darwin-arm64.tar.gz
│   └── go1.20rc2.darwin-arm64.tar.gz
├── env
├── go -> /Users/voidint/.g/versions/1.19.4
└── versions
    ├── 1.18.9
    ├── 1.19.4
    └── 1.20rc2

7 directories, 7 files
```
其中`~/.g/go`就是当前所使用的go版本，得确保`PATH`包含了`~/.g/go/bin`目录，否则就会抛出找不到go命令的错误。Windows系统下用户的家目录你可以自行搜索下。
