### ISSUE TITLE
这程序确实不错！解决了 windows 的痛点

### ISSUE THREAD

**Issue by vagra** [voidint/g#86]
我特别在知乎写了篇文章来总结我的使用经验：
https://zhuanlan.zhihu.com/p/601440880

使用中发现还有一点需要改进，就是 GOHOME 的位置。
类似于其它语言的版本管理器，它们都是把各个版本的包，安装到各自版本的对应目录下，是不是？

如果 GOHOME 是个固定的位置，那么不同版本安装的包，都会混在这个目录下，那不太科学，是不是？

所以我现在的解决方案是：
新建系统变量：
```
G_EXPERIMENTAL  true               # 必须开启这个实验特性才能让 G_HOME 生效
G_HOME          D:\Library\g       # 指定 g 的根目录
GOROOT          D:\Library\g\Go    # 这个路径是个快捷方式，指向 go 的当前版本目录
GOPATH          %GOROOT%\ext       # 使用 go mod 安装的模块都会安装到当前版本的 ext 目录下
```
Path 中添加
```
%G_HOME%\bin     # 添加这一条就可以启动 g 
%GOROOT%\bin     # 添加这一条就可以启动当前版本的 go 工具链
%GOPATH%\bin     # 通过 go mod 为当前版本的 go 安装的模块，添加这一条就可以启动
```

这样每一个版本运行 go mod 安装时会把包安装到当前版本的 go 的 ext 目录下。

这样虽然可以解决问题，但是呢，需要用户动脑筋来摸索和设置，有点儿麻烦。

有更好的解决方案吗？

**Comment by voidint** [comment]
- 谢谢你的反馈。
- 个人认为，将`GOPATH`设置为`GOROOT`下的一个子目录不属于最佳实践，并不提倡这样做。官方给的`GOPATH`默认位置是`~/go`，与`GOROOT`并无直接关联。如果执意将建议`GOPATH`设置为`GOROOT`下的某个子目录，可能的结果是执行`g uninstall`后，`GOPATH`下的文件会被意外删除。建议遵循官方给的最佳实践。

**Comment by vagra** [comment]
现在就是存在这个问题！我当时觉得我的解决方案仍然不完美的原因就是这个。只是当时没说。

如果从程序上解决，我的解决方案是：

1、在 g/ 目录下，新建 packages/ 文件夹；
2、对于每个版本的 go ，在 packages/ 里面新建一个版本号一致的子文件夹；
3、每次通过 g 选择了 go 的版本后，就在 g/ 下面新建一个软连接，叫做 home ，链接到 packages/ 里面对应版本的子目录；
4、环境变量中添加 $GOHOME = g/home/ 即可。

采用这个方案的文件夹结构示例如下：
```
go/        -> versions/1.19.5/
home/   -> packages/1.19.5/
bin/
downloads/
versions/
         1.19.5/
         1.20rc3/
packages/
         1.19.5/
         1.20rc3/
```

**Comment by voidint** [comment]
你的意思是，将`GOPATH`设置为`~/.g/home`，其软链接至`~/.g/packages/1.19.5`，并且切换 go 版本时，同步切换`~/.g/home`的目标链接目录？

我不太理解要这么做的意义。在`前go modules`时代，GOPATH下的src目录用于存放源代码（自己的代码以及第三方依赖库的代码）；现如今的`go modules`时代，GOPATH下的src目录存放源代码的烙印被弱化，更加强调的是`$GOPATH/pkg/mod`目录存放第三方依赖的功能。如果你侧重想要表达的是`~/.g/packages/1.19.5`用于存放go 1.19.5 这个版本存放该版本对应的第三方依赖，那么完全没有必要。以`gorm@v1.24.3`这个第三方依赖库为例，不管是go 1.19.5、1.19.4、1.19.3、1.19.2，都只需要一份`$GOPATH/pkg/mod/gorm.io/gorm@v1.24.3`代码，而不是每个go sdk版本下都存一份一样的代码。况且第三方依赖库的存放位置并不直接由`GOPATH`决定，而是由`GOMODCACHE`这个环境变量所决定。

**Comment by vagra** [comment]
噢，多谢解说，现在我明白了。那么我可以把 $GOHOME 设为一个固定的目录。
