### ISSUE TITLE
g install 报错

### ISSUE THREAD

**Issue by HarcourtFun** [voidint/g#88]
[g] Resource(Https://Golang.Google.Cn/Dl/Go1.20.2.Windows-386.Zip) download failed ==> Get "https://dl.google.com/go/go1.20.2.windows-386.zip": net/http: TLS handshake timeout

已经配置G_MIRROR 环境变量，看着像链接大小写的问题?请问下这个需要怎么处理

确认浏览器中用小写的格式是可以下载的

**Comment by HarcourtFun** [comment]
自己填坑，深层次原理没研究，把源码中 install.go  33行 读取环境变量改为小写，重新编译即可解决

原来
c, err := collector.NewCollector(strings.Split(os.Getenv(mirrorEnv), ",")...)

转小写
c, err := collector.NewCollector(strings.Split(strings.ToLower(os.Getenv(mirrorEnv)), ",")...)

**Comment by voidint** [comment]
更推荐的做法是修改环境变量`G_MIRROR`的值

**Comment by HarcourtFun** [comment]
> 更推荐的做法是修改环境变量`G_MIRROR`的值

G_MIRROR 的是小写的，没有问题

![image](https://user-images.githubusercontent.com/39760163/226274760-7aff8f77-3d3c-430e-8620-b3778908129d.png)

**Comment by voidint** [comment]
代码里没有额外的大小写转换，建议你排查下自身的环境变量设置。建议在运行g的命令行环境中输出下`G_MIRROR`的值。

**Comment by zfkhhh** [comment]
![image](https://user-images.githubusercontent.com/60089581/228154685-1d875360-e072-4018-9782-ec54d20764b0.png)

**Comment by voidint** [comment]
> ![image](https://user-images.githubusercontent.com/60089581/228154685-1d875360-e072-4018-9782-ec54d20764b0.png) 有点奇怪，https://golang.google.cn/dl/ 可以访问，看提示是大写了

每次执行都必现，都是大写吗？

**Comment by worshipone** [comment]
> 

是的，我也有这个问题

**Comment by voidint** [comment]
> > 
> 
> 是的，我也有这个问题

这个问题分两部分来看：
- 1、是不是由于网络问题导致的下载失败。这很好验证，同一个程序同一个`G_MIRROR`配置值，在不同的时间和不同的网络条件下是否都是安装失败。如果是，那肯定是程序的 bug ；如果不是，那么显然和`G_MIRROR`大小写之类的无关，因为只要有一次安装成功就足以说明问题。用户可以更多地关注这点，看是否是网络导致的安装失败，而不是`G_MIRROR`配置。
- 2、为什么会出现意外的大写。首先 g 的代码中应该并不存在首字母大写之类的逻辑。其次，不能保证第三方依赖或者标准库中没有，只是暂时没有发现。

**Comment by worshipone** [comment]
> > > 
> > 
> > 
> > 是的，我也有这个问题
> 
> 这个问题分两部分来看：
> 
> * 1、是不是由于网络问题导致的下载失败。这很好验证，同一个程序同一个`G_MIRROR`配置值，在不同的时间和不同的网络条件下是否都是安装失败。如果是，那肯定是程序的 bug ；如果不是，那么显然和`G_MIRROR`大小写之类的无关，因为只要有一次安装成功就足以说明问题。用户可以更多地关注这点，看是否是网络导致的安装失败，而不是`G_MIRROR`配置。
> * 2、为什么会出现意外的大写。首先 g 的代码中应该并不存在首字母大写之类的逻辑。其次，不能保证第三方依赖或者标准库中没有，只是暂时没有发现。

好滴，谢谢你的回复，使用阿里云后就可以了。
