### ISSUE TITLE
国内使用https://go.dev/dl/下载比较慢，可以考虑支持可配置

### ISSUE THREAD

**Issue by moqsien** [voidint/g#89]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

可以改用https://golang.google.cn/dl/。

我搞了一个更强大的开发环境一键配置工具[gvc](https://github.com/moqsien/gvc)。
支持go,java,python,nodejs,rust,c/c++等，还能一键安装VSCode和Neovim，后面还会支持免费VPN。
gvc是可配置的，可以用离自己更近或者更快的软件源进行配置，所有下载几乎都有相关加速，也不用操心环境变量，gvc可以帮你设置好。
gvc支持MacOS、Linux、Windows全平台。

欢迎使用和指导。

**Comment by voidint** [comment]
看过README就会知道，可以使用`G_MIRROR`环境变量来配置镜像地址。
