### ISSUE TITLE
安装的版本与go版本不匹配

### ISSUE THREAD

**Issue by zhangyf35** [voidint/g#94]
mac m1  安装了 1.19.10 是 1.17   安装的 1.20.5是1.17.6

<img width="974" alt="iShot_2023-06-11_00 54 59" src="https://github.com/voidint/g/assets/15116640/cbb9d242-8926-4ed6-81dc-da843b3f3b4d">

**Comment by voidint** [comment]
- 这个1.17.6大概率就是你之前就存在的，用`which go`查看下指向的文件名就知道了。
- 如果严格按照README中所述操作，使用`source "$HOME/.g/env"`配置SHELL环境变量，那么g安装的go指向的位置将会是`$HOME/.g/go/bin/go`。

**Comment by voidint** [comment]
g 安装go sdk是严格匹配的方式，指定安装哪个版本，就不会进行模糊匹配，要么安装失败，要么就安装指定的版本，绝不会挂羊头卖狗肉。

**Comment by zhangyf35** [comment]
> * 这个1.17.6大概率就是你之前就存在的，用`which go`查看下指向的文件名就知道了。
> * 如果严格按照README中所述操作，使用`source "$HOME/.g/env"`配置SHELL环境变量，那么g安装的go指向的位置将会是`$HOME/.g/go/bin/go`。

确实是系统自带了go， 感谢提醒
